<?php
    session_start();
    include 'header.php';

    if($_SERVER['REQUEST_METHOD'] == "GET" and isset($_GET['yes'])){
        require('setup_2fa.inc');
        $_SESSION["tfa"] = serialize($tfa);
        $_SESSION["secret"] = $secret;
?>
        <fieldset class="fieldset"><legend>Multi-Factor Authentication Setup</legend>

    <?php
        //displays QR code
        if (extension_loaded('gd') && function_exists('gd_info')) {
            //echo "PHP GD library is installed on your web server";
            echo '<p>Please scan this QR code into the authenticator app.</p>';
            echo '<img src="'.$tfa->getQRCodeImageAsDataUri('ICS 325', $secret).'">';
        }
        else {
            //display the secrete
            echo '<p><span style="color:rgb(151, 41, 41);">Required PHP GD library to draw the QR code is NOT installed on your web server.</span>'.
            '<br>The authenticator app won\'t automatically recognize it.'.
            '<br>Instead scan this QR code with <a target="_blank" href="https://play.google.com/store/apps/details?id=com.kevintesar.qrcodetoclipboard&hl=en_US">this app</a> to copy the code to your phone\'s clip-board'.
            ' then paste it into the authenticator app.'.
            '<br><img src="https://chart.googleapis.com/chart?chs=100x100&cht=qr&chl='.$secret.'" /></p>';
        }
    ?>
    
        <form action="check_2fa.php" method="post" id="mainForm">
            <p><strong>Or manually enter this secret (in blue) into the authenticator app: <?php echo '</strong><span style="color:blue; border:groove 5px;">'.chunk_split($_SESSION["secret"], 4, ' ').'</span>'; ?></p>
            <p>Next verify that the code generated by the app is correct using the field below.</p>
            <p><label for="code">Enter the code from the authenticator app here:</label>
                <input type="text" id="code" name="code" maxlength="25" size="13" class="required highlightable"/>
            </p>            
            <p><button type="submit">Verify Code</button></p>
        </form>
        </fieldset>
        
<?php
    }else {echo "<p><fieldset class=\"fieldset\">No 2FA for you.</p></fieldset>";}
    include('footer.php');

    // echo '<p> Your session ID: '.session_id().'</p>';  
    //     try {
    //         $tfa->ensureCorrectTime();
    //         echo '<span style="color:#0c0">Your hosts time seems to be correct / within margin</span>';
    //     } catch (RobThree\Auth\TwoFactorAuthException $ex) {
    //         echo '<span style="color:#c00"><b>Warning:</b> Your hosts time seems to be off: ' . $ex->getMessage().'</span>';
    //     }    
?>