<?php
    // session_start();
    include 'header.php';
    require '../SQLcreds.inc';

    // Create connection
    $conn = new mysqli($servername, $SQLuser, $SQLpswd, $dbname);
    // Check connection
    if ($conn->connect_error) {
        die("Connection failed: " . $conn->connect_error);
    }
    $username = $_SESSION['username'];
    $sql = "SELECT AES_DECRYPT(secret, UNHEX('$key')) FROM member_creds WHERE username = '$username' LIMIT 1";
    $result = $conn->query($sql);
    $row = $result -> fetch_array(MYSQLI_NUM);
    $secret = $row[0];
    $_SESSION['secret'] = $secret;
    
    // echo '<p>Youre check box: '.$_GET['2fa'].'</p>';

    if($_SERVER['REQUEST_METHOD'] == "GET" and isset($_GET['yes']) or isset($_GET['2fa'])){
        require('setup_2fa.inc');
        $_SESSION["tfa"] = serialize($tfa);
        $_SESSION["secret"] = $secret;
?>
    <fieldset class="fieldset"><legend>Multi-Factor Authentication Setup</legend>

    <?php
        //displays QR code
        if (extension_loaded('gd') && function_exists('gd_info')) {
            //echo "PHP GD library is installed on your web server";
            echo '<p>Scan this QR code using the authenticator app:</p>';
            echo '<img src="'.$tfa->getQRCodeImageAsDataUri('ICS 325', $secret).'">';
        }
        else {
            //display the secrete
            echo '<p><span style="color:rgb(151, 41, 41);">Required PHP GD library to draw the QR code is NOT installed on your web server.</span>'.
            '<br>The authenticator app won\'t automatically recognize it.'.
            '<br>Instead scan this QR code with <a target="_blank" href="https://play.google.com/store/apps/details?id=com.kevintesar.qrcodetoclipboard&hl=en_US">this app</a> to copy the code to your phone\'s clip-board'.
            ' then paste it into the authenticator app.'.
            '<br><img src="https://chart.googleapis.com/chart?chs=100x100&cht=qr&chl='.$secret.'" /></p>';
        }
    ?>    
        <form action="check_2fa.php" method="post" id="mainForm">
            <strong>Or manually enter this secret (in blue): </strong><p style="color:blue; border:groove 5px;"><?php echo chunk_split($_SESSION["secret"], 4, ' ')?></p>
            <p>Next verify that the code generated by the app is correct using the field below.</p>
            <p><label for="code">Enter the code from the authenticator app here:</label>
                <input type="text" id="code" name="code" maxlength="25" size="13" class="required highlightable"/>
            </p>            
            <p><button class="btn btn-primary" type="submit">Verify Code</button></p>
        </form>
        </fieldset>
        
<?php
    }else{
        echo "<article><p>No 2FA for you.</p></article>";
        $query = "UPDATE member_creds SET secret = NULL WHERE username = '$username'";
        $stmt = $conn->prepare($query);
        $stmt->execute();
        unset($secret);
        unset($_SESSION['secret']);
        $conn->close();
        // include('home.php');
        echo '<meta http-equiv="Refresh" content="0; url=account.php" />';
    }
    include('footer.php');
   
    // echo '<p> Your session ID: '.session_id().'</p>';  
    //     try {
    //         $tfa->ensureCorrectTime();
    //         echo '<span style="color:#0c0">Your hosts time seems to be correct / within margin</span>';
    //     } catch (RobThree\Auth\TwoFactorAuthException $ex) {
    //         echo '<span style="color:#c00"><b>Warning:</b> Your hosts time seems to be off: ' . $ex->getMessage().'</span>';
    //     }    
?>