<?php
    session_start();
    include 'header.php';

    if($_SERVER['REQUEST_METHOD'] == "GET" and isset($_GET['yes'])){
        require('setup_2fa.inc');
        $_SESSION["tfa"] = serialize($tfa);
        $_SESSION["secret"] = $secret;
?>
        <fieldset class="fieldset"><legend>MFA Setup</legend>

    <?php
        //displays QR code
        if (extension_loaded('gd') && function_exists('gd_info')) {
            //echo "PHP GD library is installed on your web server";
            echo '<br><img src="'.$tfa->getQRCodeImageAsDataUri('ICS 325', $secret).'">';
        }
        else {
            //display the secrete
            echo '<br><strong style="color:rgb(151, 41, 41);">The required PHP library to draw the QR code (GD) is not installed on your web server.</strong>';
        }
    ?>
    
        <form action="check_2fa.php" method="post" id="mainForm">
            <p><strong>Please enter this secret into your authenticator app: <?php echo '</strong><span style="color:rgb(24, 0, 160);">'.chunk_split($_SESSION["secret"], 4, ' ').'</span>'; ?></p>
            <p>Then verify that the code generated by the app is correct using the field below.</p>
            <p><label for="code">Enter the code from the authenticator app:</label>
                <input type="text" id="code" name="code" maxlength="25" size="13" class="required hilightable"/>
            </p>            
            <p><input type="submit" value="verify code" class="btn"/></p>
        </form>
        </fieldset>
        
<?php
    }else {echo "<p><fieldset class=\"fieldset\">No 2FA for you.</p></fieldset>";}

    // echo '<p> Your session ID: '.session_id().'</p>';  
    //     try {
    //         $tfa->ensureCorrectTime();
    //         echo '<span style="color:#0c0">Your hosts time seems to be correct / within margin</span>';
    //     } catch (RobThree\Auth\TwoFactorAuthException $ex) {
    //         echo '<span style="color:#c00"><b>Warning:</b> Your hosts time seems to be off: ' . $ex->getMessage().'</span>';
    //     }    
?>