<?php
ini_set('display_startup_errors',1); 
ini_set('display_errors',1);
error_reporting(-1);
    include 'header.php';
    require '../../SQLcreds.inc';

    // Create connection
    $conn = mysqli_init();
    mysqli_ssl_set($conn,NULL,NULL, $cert, NULL, NULL);
    mysqli_real_connect($conn, $servername, $SQLuser, $SQLpswd, $dbname, 3306, MYSQLI_CLIENT_SSL);
    if (mysqli_connect_errno()) {
      die('Failed to connect to MySQL: '.mysqli_connect_error());
    }
    $username = $_SESSION['username'];
    $sql = "SELECT AES_DECRYPT(secret, UNHEX('$key')) FROM member_creds WHERE username = '$username' LIMIT 1";
    $result = $conn->query($sql);
    $row = $result -> fetch_array(MYSQLI_NUM);
    $secret = $row[0];
    $_SESSION['secret'] = $secret;

    if($_SERVER['REQUEST_METHOD'] == "GET" and isset($_GET['yes']) or isset($_GET['2fa'])){
        require('setup_2fa.inc');
        $_SESSION["tfa"] = serialize($tfa);
        $_SESSION["secret"] = $secret;
?>
    <fieldset class="fieldset"><legend>Multi-Factor Authentication Setup</legend>
    <?php
        //displays QR code
        if (extension_loaded('gd') && function_exists('gd_info')) {
            //echo "PHP GD library is installed on your web server";
            echo '<p>Scan this QR code using the authenticator app:</p>';
            echo '<img src="'.$tfa->getQRCodeImageAsDataUri('ICS 325', $secret).'">';
        }
        else {
            //substitute google QR API
            echo '<p style="color:rgb(151, 41, 41);">Required PHP library to draw the QR code GD is NOT installed on this web server.</span></p>'.
            '<p>The authenticator app won\'t automatically recognize this QR code.'.
            '<br>Instead scan this QR code with a generic QR code reader then paste it into the authenticator app.'.
            '<br><img src="https://chart.googleapis.com/chart?chs=100x100&cht=qr&chl='.$secret.'" />'.
            '<br><a target="_blank" href="https://play.google.com/store/apps/details?id=com.kevintesar.qrcodetoclipboard&hl=en_US">This app </a>'.
            'copies the secret directly to the phone clip-board.</p>';
        }
    ?>    
        <form action="check_2fa.php" method="post" id="mainForm">
            <strong>Or manually enter this secret (in blue): </strong><p style="color:blue; border:groove 5px;"><?php echo chunk_split($_SESSION["secret"], 4, ' ')?></p>
            <p>Next verify that the code generated by the app is correct using the field below.</p>
            <p><label for="code">Enter the code from the authenticator app here:</label>
                <input type="text" id="code" name="code" maxlength="25" size="13"/>
            </p>            
            <p><button class="btn btn-primary" type="submit">Verify Code</button></p>
        </form>
    </fieldset>
        
<?php
    } else {
        echo "<article><p>Redirecting to your account page.</p></article>";
        $query = "UPDATE member_creds SET secret = NULL WHERE username = '$username'";
        $stmt = $conn->prepare($query);
        $stmt->execute();
        unset($secret);
        unset($_SESSION['secret']);
        $stmt -> free_result();
        $conn->close();
        echo '<meta http-equiv="Refresh" content="0; url=account.php" />';
    }    
    include('../footer.php');
   
    // echo '<p> Your session ID: '.session_id().'</p>';  
    //     try {
    //         $tfa->ensureCorrectTime();
    //         echo '<span style="color:#0c0">Your hosts time seems to be correct / within margin</span>';
    //     } catch (RobThree\Auth\TwoFactorAuthException $ex) {
    //         echo '<span style="color:#c00"><b>Warning:</b> Your hosts time seems to be off: ' . $ex->getMessage().'</span>';
    //     }    
?>